@endpoint = http://localhost:4000/api

###
GET {{endpoint}}/projects

###
POST {{endpoint}}/projects
Content-Type: application/json

{
  "name": "Build The Thing"
}

###
GET {{endpoint}}/projects/3/tasks

###
POST {{endpoint}}/projects/3/tasks
Content-Type: application/json

{
  "description": "Build A Feature",
  "notes": "Any feature... Just build SOMETHING!"
}

###
GET {{endpoint}}/projects/3/resources

###
POST {{endpoint}}/projects/3/resources
Content-Type: application/json

{
  "resource_id": 2
}

###
GET {{endpoint}}/resources

###
POST {{endpoint}}/resources
Content-Type: application/json

{
  "name": "Yes Man",
  "description": "Yes."
}